# Generated by Django 5.0 on 2024-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_remove_userdata_one_time_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
