# Generated by Django 5.0 on 2024-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_img',
            field=models.ImageField(blank=True, null=True, upload_to='call', verbose_name='Изображение'),
        ),
    ]
