# Generated by Django 5.0 on 2024-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_call_call_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_img_min',
            field=models.ImageField(blank=True, null=True, upload_to='call', verbose_name='Изображение min'),
        ),
    ]
