# Generated by Django 5.0 on 2024-01-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_call_img_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_img_min',
        ),
    ]
